
package mx.com.dti.os.service.soap.configuracion.modulos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ModulosService", targetNamespace = "http://modulos.configuracion.soap.eservices.os.planetmedia.com.mx")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ModulosService {


    /**
     * 
     * @param guardarModuloRequest
     * @return
     *     returns mx.com.planetmedia.os.eservices.soap.configuracion.modulos.ModulosResponseVO
     * @throws ServiceException_Exception
     */
    @WebMethod(operationName = "GuardaModulo")
    @WebResult(name = "GuardarModuloResponse", targetNamespace = "http://modulos.configuracion.soap.eservices.os.planetmedia.com.mx")
    @RequestWrapper(localName = "GuardaModulo", targetNamespace = "http://modulos.configuracion.soap.eservices.os.planetmedia.com.mx", className = "mx.com.planetmedia.os.eservices.soap.configuracion.modulos.GuardaModulo")
    @ResponseWrapper(localName = "GuardaModuloResponse", targetNamespace = "http://modulos.configuracion.soap.eservices.os.planetmedia.com.mx", className = "mx.com.planetmedia.os.eservices.soap.configuracion.modulos.GuardaModuloResponse")
    public ModulosResponseVO guardaModulo(
        @WebParam(name = "GuardarModuloRequest", targetNamespace = "")
        ModuloRequestVO guardarModuloRequest)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns mx.com.planetmedia.os.eservices.soap.configuracion.modulos.ModulosResponseVO
     * @throws ServiceException_Exception
     */
    @WebMethod(operationName = "ConsultarCatalogoModulos")
    @WebResult(name = "CatalogoModulosResponse", targetNamespace = "http://modulos.configuracion.soap.eservices.os.planetmedia.com.mx")
    @RequestWrapper(localName = "ConsultarCatalogoModulos", targetNamespace = "http://modulos.configuracion.soap.eservices.os.planetmedia.com.mx", className = "mx.com.planetmedia.os.eservices.soap.configuracion.modulos.ConsultarCatalogoModulos")
    @ResponseWrapper(localName = "ConsultarCatalogoModulosResponse", targetNamespace = "http://modulos.configuracion.soap.eservices.os.planetmedia.com.mx", className = "mx.com.planetmedia.os.eservices.soap.configuracion.modulos.ConsultarCatalogoModulosResponse")
    public ModulosResponseVO consultarCatalogoModulos()
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param obtenerMenuRequest
     * @return
     *     returns mx.com.planetmedia.os.eservices.soap.configuracion.modulos.ModulosResponseVO
     * @throws ServiceException_Exception
     */
    @WebMethod(operationName = "ObtenerMenu")
    @WebResult(name = "ObtenerMenuResponse", targetNamespace = "http://modulos.configuracion.soap.eservices.os.planetmedia.com.mx")
    @RequestWrapper(localName = "ObtenerMenu", targetNamespace = "http://modulos.configuracion.soap.eservices.os.planetmedia.com.mx", className = "mx.com.planetmedia.os.eservices.soap.configuracion.modulos.ObtenerMenu")
    @ResponseWrapper(localName = "ObtenerMenuResponse", targetNamespace = "http://modulos.configuracion.soap.eservices.os.planetmedia.com.mx", className = "mx.com.planetmedia.os.eservices.soap.configuracion.modulos.ObtenerMenuResponse")
    public ModulosResponseVO obtenerMenu(
        @WebParam(name = "ObtenerMenuRequest", targetNamespace = "")
        FacRolRequestVO obtenerMenuRequest)
        throws ServiceException_Exception
    ;

}
