
package mx.com.dti.os.service.soap.configuracion.modulos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ModulosServiceWS", targetNamespace = "http://modulos.configuracion.soap.service.os.dti.com.mx", wsdlLocation = "http://192.168.79.88:8080/eservices-soap/ModulosServiceWS?wsdl")
public class ModulosServiceWS
    extends Service
{

    private final static URL MODULOSSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException MODULOSSERVICEWS_EXCEPTION;
    private final static QName MODULOSSERVICEWS_QNAME = new QName("http://modulos.configuracion.soap.service.os.dti.com.mx", "ModulosServiceWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.79.88:8080/eservices-soap/ModulosServiceWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODULOSSERVICEWS_WSDL_LOCATION = url;
        MODULOSSERVICEWS_EXCEPTION = e;
    }

    public ModulosServiceWS() {
        super(__getWsdlLocation(), MODULOSSERVICEWS_QNAME);
    }

    public ModulosServiceWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODULOSSERVICEWS_QNAME, features);
    }

    public ModulosServiceWS(URL wsdlLocation) {
        super(wsdlLocation, MODULOSSERVICEWS_QNAME);
    }

    public ModulosServiceWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODULOSSERVICEWS_QNAME, features);
    }

    public ModulosServiceWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModulosServiceWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModulosService
     */
    @WebEndpoint(name = "ModulosServiceImplPort")
    public ModulosService getModulosServiceImplPort() {
        return super.getPort(new QName("http://modulos.configuracion.soap.service.os.dti.com.mx", "ModulosServiceImplPort"), ModulosService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModulosService
     */
    @WebEndpoint(name = "ModulosServiceImplPort")
    public ModulosService getModulosServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://modulos.configuracion.soap.service.os.dti.com.mx", "ModulosServiceImplPort"), ModulosService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODULOSSERVICEWS_EXCEPTION!= null) {
            throw MODULOSSERVICEWS_EXCEPTION;
        }
        return MODULOSSERVICEWS_WSDL_LOCATION;
    }

}
