
package mx.com.dti.os.service.soap.configuracion.servicios;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.dti.os.service.vo.configuracion.servicios.ServiciosResponseVO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiciosService", targetNamespace = "http://servicios.configuracion.soap.eservices.os.planetmedia.com.mx")
@XmlSeeAlso({
    mx.com.dti.os.service.vo.configuracion.servicios.ObjectFactory.class,
    mx.com.dti.os.service.soap.configuracion.servicios.ObjectFactory.class
})
public interface ServiciosService {


    /**
     * 
     * @return
     *     returns mx.com.planetmedia.os.eservices.common.vo.configuracion.servicios.ServiciosResponseVO
     * @throws ServiceException_Exception
     */
    @WebMethod(operationName = "ConsultarCatalogoServicios")
    @WebResult(name = "CatalogoServiciosResponse", targetNamespace = "http://servicios.configuracion.soap.eservices.os.planetmedia.com.mx")
    @RequestWrapper(localName = "ConsultarCatalogoServicios", targetNamespace = "http://servicios.configuracion.soap.eservices.os.planetmedia.com.mx", className = "mx.com.planetmedia.os.eservices.soap.configuracion.servicios.ConsultarCatalogoServicios")
    @ResponseWrapper(localName = "ConsultarCatalogoServiciosResponse", targetNamespace = "http://servicios.configuracion.soap.eservices.os.planetmedia.com.mx", className = "mx.com.planetmedia.os.eservices.soap.configuracion.servicios.ConsultarCatalogoServiciosResponse")
    public ServiciosResponseVO consultarCatalogoServicios()
        throws ServiceException_Exception
    ;

}
