
package mx.com.dti.os.service.soap.configuracion.states;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StateService", targetNamespace = "http://states.configuracion.soap.eservices.os.planetmedia.com.mx")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StateService {


    /**
     * 
     * @return
     *     returns mx.com.planetmedia.os.eservices.soap.configuracion.states.CatStateResponseVO
     * @throws ServiceException_Exception
     */
    @WebMethod(operationName = "ConsultarCatalogoStates")
    @WebResult(name = "CatalogoStatesResponse", targetNamespace = "http://states.configuracion.soap.eservices.os.planetmedia.com.mx")
    @RequestWrapper(localName = "ConsultarCatalogoStates", targetNamespace = "http://states.configuracion.soap.eservices.os.planetmedia.com.mx", className = "mx.com.planetmedia.os.eservices.soap.configuracion.states.ConsultarCatalogoStates")
    @ResponseWrapper(localName = "ConsultarCatalogoStatesResponse", targetNamespace = "http://states.configuracion.soap.eservices.os.planetmedia.com.mx", className = "mx.com.planetmedia.os.eservices.soap.configuracion.states.ConsultarCatalogoStatesResponse")
    public CatStateResponseVO consultarCatalogoStates()
        throws ServiceException_Exception
    ;

}
