
package mx.com.dti.os.service.soap.configuracion.rolfac;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RolFacServiceWS", targetNamespace = "http://rolfac.configuracion.soap.service.os.dti.com.mx", wsdlLocation = "http://192.168.79.88:8080/eservices-soap/RolFacServiceWS?wsdl")
public class RolFacServiceWS
    extends Service
{

    private final static URL ROLFACSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException ROLFACSERVICEWS_EXCEPTION;
    private final static QName ROLFACSERVICEWS_QNAME = new QName("http://rolfac.configuracion.soap.service.os.dti.com.mx", "RolFacServiceWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.79.88:8080/eservices-soap/RolFacServiceWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROLFACSERVICEWS_WSDL_LOCATION = url;
        ROLFACSERVICEWS_EXCEPTION = e;
    }

    public RolFacServiceWS() {
        super(__getWsdlLocation(), ROLFACSERVICEWS_QNAME);
    }

    public RolFacServiceWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROLFACSERVICEWS_QNAME, features);
    }

    public RolFacServiceWS(URL wsdlLocation) {
        super(wsdlLocation, ROLFACSERVICEWS_QNAME);
    }

    public RolFacServiceWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROLFACSERVICEWS_QNAME, features);
    }

    public RolFacServiceWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RolFacServiceWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RolFacService
     */
    @WebEndpoint(name = "RolFacServiceImplPort")
    public RolFacService getRolFacServiceImplPort() {
        return super.getPort(new QName("http://rolfac.configuracion.soap.service.os.dti.com.mx", "RolFacServiceImplPort"), RolFacService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RolFacService
     */
    @WebEndpoint(name = "RolFacServiceImplPort")
    public RolFacService getRolFacServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rolfac.configuracion.soap.service.os.dti.com.mx", "RolFacServiceImplPort"), RolFacService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROLFACSERVICEWS_EXCEPTION!= null) {
            throw ROLFACSERVICEWS_EXCEPTION;
        }
        return ROLFACSERVICEWS_WSDL_LOCATION;
    }

}
