
package mx.com.dti.os.service.soap.configuracion.roles;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RolServiceWS", targetNamespace = "http://roles.configuracion.soap.service.os.dti.com.mx", wsdlLocation = "http://192.168.79.88:8080/eservices-soap/RolServiceWS?wsdl")
public class RolServiceWS
    extends Service
{

    private final static URL ROLSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException ROLSERVICEWS_EXCEPTION;
    private final static QName ROLSERVICEWS_QNAME = new QName("http://roles.configuracion.soap.service.os.dti.com.mx", "RolServiceWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.79.88:8080/eservices-soap/RolServiceWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROLSERVICEWS_WSDL_LOCATION = url;
        ROLSERVICEWS_EXCEPTION = e;
    }

    public RolServiceWS() {
        super(__getWsdlLocation(), ROLSERVICEWS_QNAME);
    }

    public RolServiceWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROLSERVICEWS_QNAME, features);
    }

    public RolServiceWS(URL wsdlLocation) {
        super(wsdlLocation, ROLSERVICEWS_QNAME);
    }

    public RolServiceWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROLSERVICEWS_QNAME, features);
    }

    public RolServiceWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RolServiceWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RolService
     */
    @WebEndpoint(name = "RolServiceImplPort")
    public RolService getRolServiceImplPort() {
        return super.getPort(new QName("http://roles.configuracion.soap.service.os.dti.com.mx", "RolServiceImplPort"), RolService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RolService
     */
    @WebEndpoint(name = "RolServiceImplPort")
    public RolService getRolServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://roles.configuracion.soap.service.os.dti.com.mx", "RolServiceImplPort"), RolService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROLSERVICEWS_EXCEPTION!= null) {
            throw ROLSERVICEWS_EXCEPTION;
        }
        return ROLSERVICEWS_WSDL_LOCATION;
    }

}
