package mx.com.dti.os.service.persistence.entity.configuracion;
// Generated 10-ago-2016 17:14:31 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CatServicios generated by hbm2java
 */
@Entity
@Table(name = "CAT_SERVICIOS")
public class CatServicios implements java.io.Serializable {

	private Integer idServicio;
	private String servicio;
	private String clave;
	private String descripcion;
	private Date fecAlta;
	private Date fecBaja;
	private Boolean estatus;

	public CatServicios() {
	}

	public CatServicios(Integer idServicio, String servicio, Date fecAlta, Boolean estatus) {
		this.idServicio = idServicio;
		this.servicio = servicio;
		this.fecAlta = fecAlta;
		this.estatus = estatus;
	}

	public CatServicios(Integer idServicio, String servicio, String clave, String descripcion, Date fecAlta, Date fecBaja,
			Boolean estatus) {
		this.idServicio = idServicio;
		this.servicio = servicio;
		this.clave = clave;
		this.descripcion = descripcion;
		this.fecAlta = fecAlta;
		this.fecBaja = fecBaja;
		this.estatus = estatus;
	}

	@Id

	@Column(name = "ID_SERVICIO", unique = true, nullable = false)
	public Integer getIdServicio() {
		return this.idServicio;
	}

	public void setIdServicio(Integer idServicio) {
		this.idServicio = idServicio;
	}

	@Column(name = "SERVICIO", nullable = false, length = 200)
	public String getServicio() {
		return this.servicio;
	}

	public void setServicio(String servicio) {
		this.servicio = servicio;
	}

	@Column(name = "CLAVE", length = 50)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "DESCRIPCION", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_ALTA", nullable = false, length = 23)
	public Date getFecAlta() {
		return this.fecAlta;
	}

	public void setFecAlta(Date fecAlta) {
		this.fecAlta = fecAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_BAJA", length = 23)
	public Date getFecBaja() {
		return this.fecBaja;
	}

	public void setFecBaja(Date fecBaja) {
		this.fecBaja = fecBaja;
	}

	@Column(name = "ESTATUS", nullable = false, length = 1)
	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}

}
