package mx.com.dti.os.service.persistence.entity.configuracion;
// Generated 19-ago-2016 12:32:09 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblModuloRegla generated by hbm2java
 */
@Entity
@Table(name = "TBL_MODULO_REGLA")
public class TblModuloRegla implements java.io.Serializable {

	private Integer idModRegla;
	private CatFacultad catFacultad;
	private CatModulo catModulo;
	private CatServicios catServicios;
	private String operLogico;
	private Date fecAlta;
	private Date fecMod;
	private Date fecBaja;
	private Boolean estatus;

	public TblModuloRegla() {
	}

	public TblModuloRegla(Date fecAlta, Boolean estatus) {
		this.fecAlta = fecAlta;
		this.estatus = estatus;
	}

	public TblModuloRegla(CatFacultad catFacultad, CatModulo catModulo, CatServicios catServicios, String operLogico,
			Date fecAlta, Date fecMod, Date fecBaja, Boolean estatus) {
		this.catFacultad = catFacultad;
		this.catModulo = catModulo;
		this.catServicios = catServicios;
		this.operLogico = operLogico;
		this.fecAlta = fecAlta;
		this.fecMod = fecMod;
		this.fecBaja = fecBaja;
		this.estatus = estatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_MOD_REGLA", unique = true, nullable = false)
	public Integer getIdModRegla() {
		return this.idModRegla;
	}

	public void setIdModRegla(Integer idModRegla) {
		this.idModRegla = idModRegla;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FAC")
	public CatFacultad getCatFacultad() {
		return this.catFacultad;
	}

	public void setCatFacultad(CatFacultad catFacultad) {
		this.catFacultad = catFacultad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MOD")
	public CatModulo getCatModulo() {
		return this.catModulo;
	}

	public void setCatModulo(CatModulo catModulo) {
		this.catModulo = catModulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SERVICIO")
	public CatServicios getCatServicios() {
		return this.catServicios;
	}

	public void setCatServicios(CatServicios catServicios) {
		this.catServicios = catServicios;
	}

	@Column(name = "OPER_LOGICO", length = 10)
	public String getOperLogico() {
		return this.operLogico;
	}

	public void setOperLogico(String operLogico) {
		this.operLogico = operLogico;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_ALTA", nullable = false, length = 19)
	public Date getFecAlta() {
		return this.fecAlta;
	}

	public void setFecAlta(Date fecAlta) {
		this.fecAlta = fecAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_MOD", length = 19)
	public Date getFecMod() {
		return this.fecMod;
	}

	public void setFecMod(Date fecMod) {
		this.fecMod = fecMod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_BAJA", length = 19)
	public Date getFecBaja() {
		return this.fecBaja;
	}

	public void setFecBaja(Date fecBaja) {
		this.fecBaja = fecBaja;
	}

	@Column(name = "ESTATUS", nullable = false, length = 1)
	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}

}
