
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.sistran.ArrayOfCatalogoCoberturas;
import org.datacontract.schemas._2004._07.sistran.ArrayOfConsultaCatalogoFormaPago;
import org.datacontract.schemas._2004._07.sistran.ArrayOfPlanCotizar;
import org.datacontract.schemas._2004._07.sistran.AutenticacionRespuesta;
import org.datacontract.schemas._2004._07.sistran.CatalogoCPRespuestas;
import org.datacontract.schemas._2004._07.sistran.CatalogoCalcularRFC;
import org.datacontract.schemas._2004._07.sistran.CatalogoColoniaRespuestas;
import org.datacontract.schemas._2004._07.sistran.CatalogoCuestionarioConocimiento;
import org.datacontract.schemas._2004._07.sistran.CatalogoCuestionarioMedico;
import org.datacontract.schemas._2004._07.sistran.CatalogoEstadosRespuestas;
import org.datacontract.schemas._2004._07.sistran.CatalogoFrecuenciaBebida;
import org.datacontract.schemas._2004._07.sistran.CatalogoFrecuenciaDeporte;
import org.datacontract.schemas._2004._07.sistran.CatalogoFrecuenciaFuma;
import org.datacontract.schemas._2004._07.sistran.CatalogoMunicipioRespuestas;
import org.datacontract.schemas._2004._07.sistran.CatalogoOcupacionRepuestas;
import org.datacontract.schemas._2004._07.sistran.CatalogoProductosRespuestas;
import org.datacontract.schemas._2004._07.sistran.CatalogoTipoCliente;
import org.datacontract.schemas._2004._07.sistran.CatalogoTipoDeporte;
import org.datacontract.schemas._2004._07.sistran.CatalogoTipoIdentificacion;
import org.datacontract.schemas._2004._07.sistran.CatalogoTipoParentesco;
import org.datacontract.schemas._2004._07.sistran.ClaseRespuesta;
import org.datacontract.schemas._2004._07.sistran.LoginNormalRespuesta;
import org.datacontract.schemas._2004._07.sistran.LoginRespuesta;
import org.datacontract.schemas._2004._07.sistran.Modulos;
import org.datacontract.schemas._2004._07.sistran.RecuperaClaveRespuesta;
import org.datacontract.schemas._2004._07.sistran.RespuestaTarifa;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.sistran.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @param usuario
     * @param password
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.LoginNormalRespuesta
     */
    @WebMethod(action = "http://tempuri.org/IService/loginNormal")
    @WebResult(name = "loginNormalResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "loginNormal", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginNormal")
    @ResponseWrapper(localName = "loginNormalResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginNormalResponse")
    public LoginNormalRespuesta loginNormal(
        @WebParam(name = "Usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param confirmarContrasenia
     * @param nombre
     * @param contrasenia
     * @param materno
     * @param paterno
     * @param telefonoFijo
     * @param telefonoCelular
     * @param correo
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.LoginRespuesta
     */
    @WebMethod(action = "http://tempuri.org/IService/loginRegistro")
    @WebResult(name = "loginRegistroResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "loginRegistro", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginRegistro")
    @ResponseWrapper(localName = "loginRegistroResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginRegistroResponse")
    public LoginRespuesta loginRegistro(
        @WebParam(name = "nombre", targetNamespace = "http://tempuri.org/")
        String nombre,
        @WebParam(name = "paterno", targetNamespace = "http://tempuri.org/")
        String paterno,
        @WebParam(name = "materno", targetNamespace = "http://tempuri.org/")
        String materno,
        @WebParam(name = "correo", targetNamespace = "http://tempuri.org/")
        String correo,
        @WebParam(name = "contrasenia", targetNamespace = "http://tempuri.org/")
        String contrasenia,
        @WebParam(name = "confirmarContrasenia", targetNamespace = "http://tempuri.org/")
        String confirmarContrasenia,
        @WebParam(name = "telefonoCelular", targetNamespace = "http://tempuri.org/")
        String telefonoCelular,
        @WebParam(name = "telefonoFijo", targetNamespace = "http://tempuri.org/")
        String telefonoFijo);

    /**
     * 
     * @param codigo
     * @param idCodigo
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.AutenticacionRespuesta
     */
    @WebMethod(action = "http://tempuri.org/IService/loginValidarSMS")
    @WebResult(name = "loginValidarSMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "loginValidarSMS", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginValidarSMS")
    @ResponseWrapper(localName = "loginValidarSMSResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginValidarSMSResponse")
    public AutenticacionRespuesta loginValidarSMS(
        @WebParam(name = "idCodigo", targetNamespace = "http://tempuri.org/")
        String idCodigo,
        @WebParam(name = "codigo", targetNamespace = "http://tempuri.org/")
        String codigo);

    /**
     * 
     * @param correo
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.RecuperaClaveRespuesta
     */
    @WebMethod(action = "http://tempuri.org/IService/loginRecuperaClaveCorreo")
    @WebResult(name = "loginRecuperaClaveCorreoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "loginRecuperaClaveCorreo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginRecuperaClaveCorreo")
    @ResponseWrapper(localName = "loginRecuperaClaveCorreoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginRecuperaClaveCorreoResponse")
    public RecuperaClaveRespuesta loginRecuperaClaveCorreo(
        @WebParam(name = "correo", targetNamespace = "http://tempuri.org/")
        String correo);

    /**
     * 
     * @param contraseniaNueva
     * @param correo
     * @param contraseniaAnterior
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.RecuperaClaveRespuesta
     */
    @WebMethod(action = "http://tempuri.org/IService/loginCambiarContrasenia")
    @WebResult(name = "loginCambiarContraseniaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "loginCambiarContrasenia", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginCambiarContrasenia")
    @ResponseWrapper(localName = "loginCambiarContraseniaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginCambiarContraseniaResponse")
    public RecuperaClaveRespuesta loginCambiarContrasenia(
        @WebParam(name = "correo", targetNamespace = "http://tempuri.org/")
        String correo,
        @WebParam(name = "ContraseniaAnterior", targetNamespace = "http://tempuri.org/")
        String contraseniaAnterior,
        @WebParam(name = "ContraseniaNueva", targetNamespace = "http://tempuri.org/")
        String contraseniaNueva);

    /**
     * 
     * @param idProducto
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.ArrayOfPlanCotizar
     */
    @WebMethod(operationName = "ConsultaCatalogoPlanes", action = "http://tempuri.org/IService/ConsultaCatalogoPlanes")
    @WebResult(name = "ConsultaCatalogoPlanesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaCatalogoPlanes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoPlanes")
    @ResponseWrapper(localName = "ConsultaCatalogoPlanesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoPlanesResponse")
    public ArrayOfPlanCotizar consultaCatalogoPlanes(
        @WebParam(name = "idProducto", targetNamespace = "http://tempuri.org/")
        Integer idProducto);

    /**
     * 
     * @param idProducto
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.ArrayOfCatalogoCoberturas
     */
    @WebMethod(operationName = "ConsultaCatalogoCoberturas", action = "http://tempuri.org/IService/ConsultaCatalogoCoberturas")
    @WebResult(name = "ConsultaCatalogoCoberturasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaCatalogoCoberturas", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoCoberturas")
    @ResponseWrapper(localName = "ConsultaCatalogoCoberturasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoCoberturasResponse")
    public ArrayOfCatalogoCoberturas consultaCatalogoCoberturas(
        @WebParam(name = "idProducto", targetNamespace = "http://tempuri.org/")
        Integer idProducto);

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.CatalogoProductosRespuestas
     */
    @WebMethod(operationName = "ConsultaCatalogoProductos", action = "http://tempuri.org/IService/ConsultaCatalogoProductos")
    @WebResult(name = "ConsultaCatalogoProductosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaCatalogoProductos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoProductos")
    @ResponseWrapper(localName = "ConsultaCatalogoProductosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoProductosResponse")
    public CatalogoProductosRespuestas consultaCatalogoProductos();

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.CatalogoCuestionarioConocimiento
     */
    @WebMethod(operationName = "ConsultaCatalogoCuestionario", action = "http://tempuri.org/IService/ConsultaCatalogoCuestionario")
    @WebResult(name = "ConsultaCatalogoCuestionarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaCatalogoCuestionario", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoCuestionario")
    @ResponseWrapper(localName = "ConsultaCatalogoCuestionarioResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoCuestionarioResponse")
    public CatalogoCuestionarioConocimiento consultaCatalogoCuestionario();

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.CatalogoCuestionarioMedico
     */
    @WebMethod(operationName = "ConsultaCatalogoMedico", action = "http://tempuri.org/IService/ConsultaCatalogoMedico")
    @WebResult(name = "ConsultaCatalogoMedicoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaCatalogoMedico", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoMedico")
    @ResponseWrapper(localName = "ConsultaCatalogoMedicoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoMedicoResponse")
    public CatalogoCuestionarioMedico consultaCatalogoMedico();

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.CatalogoFrecuenciaBebida
     */
    @WebMethod(operationName = "ConsultaCatalogoBebida", action = "http://tempuri.org/IService/ConsultaCatalogoBebida")
    @WebResult(name = "ConsultaCatalogoBebidaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaCatalogoBebida", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoBebida")
    @ResponseWrapper(localName = "ConsultaCatalogoBebidaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoBebidaResponse")
    public CatalogoFrecuenciaBebida consultaCatalogoBebida();

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.CatalogoFrecuenciaDeporte
     */
    @WebMethod(operationName = "ConsultaCatalogoDeporte", action = "http://tempuri.org/IService/ConsultaCatalogoDeporte")
    @WebResult(name = "ConsultaCatalogoDeporteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaCatalogoDeporte", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoDeporte")
    @ResponseWrapper(localName = "ConsultaCatalogoDeporteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoDeporteResponse")
    public CatalogoFrecuenciaDeporte consultaCatalogoDeporte();

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.CatalogoFrecuenciaFuma
     */
    @WebMethod(operationName = "ConsultaCatalogoFuma", action = "http://tempuri.org/IService/ConsultaCatalogoFuma")
    @WebResult(name = "ConsultaCatalogoFumaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaCatalogoFuma", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoFuma")
    @ResponseWrapper(localName = "ConsultaCatalogoFumaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoFumaResponse")
    public CatalogoFrecuenciaFuma consultaCatalogoFuma();

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.CatalogoTipoParentesco
     */
    @WebMethod(operationName = "ConsultaCatalogoParentesco", action = "http://tempuri.org/IService/ConsultaCatalogoParentesco")
    @WebResult(name = "ConsultaCatalogoParentescoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaCatalogoParentesco", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoParentesco")
    @ResponseWrapper(localName = "ConsultaCatalogoParentescoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoParentescoResponse")
    public CatalogoTipoParentesco consultaCatalogoParentesco();

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.CatalogoTipoCliente
     */
    @WebMethod(operationName = "ConsultaCatalogoCliente", action = "http://tempuri.org/IService/ConsultaCatalogoCliente")
    @WebResult(name = "ConsultaCatalogoClienteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaCatalogoCliente", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoCliente")
    @ResponseWrapper(localName = "ConsultaCatalogoClienteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoClienteResponse")
    public CatalogoTipoCliente consultaCatalogoCliente();

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.CatalogoTipoDeporte
     */
    @WebMethod(operationName = "ConsultaCatalogoTDeporte", action = "http://tempuri.org/IService/ConsultaCatalogoTDeporte")
    @WebResult(name = "ConsultaCatalogoTDeporteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaCatalogoTDeporte", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoTDeporte")
    @ResponseWrapper(localName = "ConsultaCatalogoTDeporteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoTDeporteResponse")
    public CatalogoTipoDeporte consultaCatalogoTDeporte();

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.CatalogoTipoIdentificacion
     */
    @WebMethod(operationName = "ConsultaCatalogoTIdentificacion", action = "http://tempuri.org/IService/ConsultaCatalogoTIdentificacion")
    @WebResult(name = "ConsultaCatalogoTIdentificacionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaCatalogoTIdentificacion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoTIdentificacion")
    @ResponseWrapper(localName = "ConsultaCatalogoTIdentificacionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoTIdentificacionResponse")
    public CatalogoTipoIdentificacion consultaCatalogoTIdentificacion();

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.CatalogoEstadosRespuestas
     */
    @WebMethod(operationName = "ConsultaCatalogoEstados", action = "http://tempuri.org/IService/ConsultaCatalogoEstados")
    @WebResult(name = "ConsultaCatalogoEstadosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaCatalogoEstados", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoEstados")
    @ResponseWrapper(localName = "ConsultaCatalogoEstadosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoEstadosResponse")
    public CatalogoEstadosRespuestas consultaCatalogoEstados();

    /**
     * 
     * @param claveEstado
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.CatalogoMunicipioRespuestas
     */
    @WebMethod(operationName = "ConsultaCatalogoMunicipio", action = "http://tempuri.org/IService/ConsultaCatalogoMunicipio")
    @WebResult(name = "ConsultaCatalogoMunicipioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaCatalogoMunicipio", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoMunicipio")
    @ResponseWrapper(localName = "ConsultaCatalogoMunicipioResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoMunicipioResponse")
    public CatalogoMunicipioRespuestas consultaCatalogoMunicipio(
        @WebParam(name = "claveEstado", targetNamespace = "http://tempuri.org/")
        String claveEstado);

    /**
     * 
     * @param claveEstado
     * @param claveMunicipio
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.CatalogoColoniaRespuestas
     */
    @WebMethod(operationName = "ConsultaCatalogoColonia", action = "http://tempuri.org/IService/ConsultaCatalogoColonia")
    @WebResult(name = "ConsultaCatalogoColoniaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaCatalogoColonia", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoColonia")
    @ResponseWrapper(localName = "ConsultaCatalogoColoniaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoColoniaResponse")
    public CatalogoColoniaRespuestas consultaCatalogoColonia(
        @WebParam(name = "claveEstado", targetNamespace = "http://tempuri.org/")
        String claveEstado,
        @WebParam(name = "claveMunicipio", targetNamespace = "http://tempuri.org/")
        String claveMunicipio);

    /**
     * 
     * @param cp
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.CatalogoCPRespuestas
     */
    @WebMethod(operationName = "ConsultaCatalogoPostal", action = "http://tempuri.org/IService/ConsultaCatalogoPostal")
    @WebResult(name = "ConsultaCatalogoPostalResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaCatalogoPostal", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoPostal")
    @ResponseWrapper(localName = "ConsultaCatalogoPostalResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoPostalResponse")
    public CatalogoCPRespuestas consultaCatalogoPostal(
        @WebParam(name = "CP", targetNamespace = "http://tempuri.org/")
        String cp);

    /**
     * 
     * @param peNModulo
     * @param idPaquete
     * @param peNPagoId
     * @param idProducto
     * @param fecNacimiento
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.RespuestaTarifa
     */
    @WebMethod(operationName = "ConsultaTarifas", action = "http://tempuri.org/IService/ConsultaTarifas")
    @WebResult(name = "ConsultaTarifasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaTarifas", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaTarifas")
    @ResponseWrapper(localName = "ConsultaTarifasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaTarifasResponse")
    public RespuestaTarifa consultaTarifas(
        @WebParam(name = "idProducto", targetNamespace = "http://tempuri.org/")
        Integer idProducto,
        @WebParam(name = "idPaquete", targetNamespace = "http://tempuri.org/")
        Integer idPaquete,
        @WebParam(name = "pe_n_pago_id", targetNamespace = "http://tempuri.org/")
        Integer peNPagoId,
        @WebParam(name = "Fec_Nacimiento", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar fecNacimiento,
        @WebParam(name = "pe_n_modulo", targetNamespace = "http://tempuri.org/")
        Integer peNModulo);

    /**
     * 
     * @param idProducto
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.ArrayOfConsultaCatalogoFormaPago
     */
    @WebMethod(operationName = "CotizaFormaDePago", action = "http://tempuri.org/IService/CotizaFormaDePago")
    @WebResult(name = "CotizaFormaDePagoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CotizaFormaDePago", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CotizaFormaDePago")
    @ResponseWrapper(localName = "CotizaFormaDePagoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CotizaFormaDePagoResponse")
    public ArrayOfConsultaCatalogoFormaPago cotizaFormaDePago(
        @WebParam(name = "idProducto", targetNamespace = "http://tempuri.org/")
        Integer idProducto);

    /**
     * 
     * @param idProducto
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.Modulos
     */
    @WebMethod(operationName = "ConsultaModulos", action = "http://tempuri.org/IService/ConsultaModulos")
    @WebResult(name = "ConsultaModulosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaModulos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaModulos")
    @ResponseWrapper(localName = "ConsultaModulosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaModulosResponse")
    public Modulos consultaModulos(
        @WebParam(name = "idProducto", targetNamespace = "http://tempuri.org/")
        Integer idProducto);

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.CatalogoOcupacionRepuestas
     */
    @WebMethod(operationName = "ConsultaCatalogoOcupaciones", action = "http://tempuri.org/IService/ConsultaCatalogoOcupaciones")
    @WebResult(name = "ConsultaCatalogoOcupacionesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaCatalogoOcupaciones", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoOcupaciones")
    @ResponseWrapper(localName = "ConsultaCatalogoOcupacionesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaCatalogoOcupacionesResponse")
    public CatalogoOcupacionRepuestas consultaCatalogoOcupaciones();

    /**
     * 
     * @param peVCCORREO
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.ClaseRespuesta
     */
    @WebMethod(operationName = "FinalizaSesion", action = "http://tempuri.org/IService/FinalizaSesion")
    @WebResult(name = "FinalizaSesionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FinalizaSesion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FinalizaSesion")
    @ResponseWrapper(localName = "FinalizaSesionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FinalizaSesionResponse")
    public ClaseRespuesta finalizaSesion(
        @WebParam(name = "PE_VC_CORREO", targetNamespace = "http://tempuri.org/")
        String peVCCORREO);

    /**
     * 
     * @param peVCNOMBRES
     * @param peVCAPMATERNO
     * @param peVCFECHANACIMIENTO
     * @param peVCAPPATERNO
     * @return
     *     returns org.datacontract.schemas._2004._07.sistran.CatalogoCalcularRFC
     */
    @WebMethod(operationName = "Calcula_RFC", action = "http://tempuri.org/IService/Calcula_RFC")
    @WebResult(name = "Calcula_RFCResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Calcula_RFC", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalculaRFC")
    @ResponseWrapper(localName = "Calcula_RFCResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalculaRFCResponse")
    public CatalogoCalcularRFC calculaRFC(
        @WebParam(name = "PE_VC_NOMBRES", targetNamespace = "http://tempuri.org/")
        String peVCNOMBRES,
        @WebParam(name = "PE_VC_APPATERNO", targetNamespace = "http://tempuri.org/")
        String peVCAPPATERNO,
        @WebParam(name = "PE_VC_APMATERNO", targetNamespace = "http://tempuri.org/")
        String peVCAPMATERNO,
        @WebParam(name = "PE_VC_FECHA_NACIMIENTO", targetNamespace = "http://tempuri.org/")
        String peVCFECHANACIMIENTO);

}
